export const bayData = 
  [
    {
      title: '에스프레소',
      src: 'https://coffeebay.com/upload/menu/file_20200715141807.png',
      desc: '다크 초콜릿의 진한 풍미와 고소함을 즐길 수 있는 에스프레소 음료',
      category: 'coffee',
      ml: 30,
      kcal: 5,
      sugar: 0,
      caffeine: 90,
    },
    {
      title: '아이스 카페 아메리카노',
      src: 'https://coffeebay.com/upload/menu/file_20200715135632.png',
      desc: '베이만의 정통 에스프레소에 물을 첨가하여 깔끔하고 시원하게 즐기는 에스프레소 음료',
      category: 'coffee',
      ml: 360,
      kcal: 5,
      sugar: 0,
      caffeine: 90,
    },
    {
      title: '아이스 카페 라떼',
      src: 'https://coffeebay.com/upload/menu/file_20200715141013.png',
      desc: '진한 에스프레소에 차가운 우유를 더해 더욱 부드럽고 고소한 커피 음료',
      category: 'coffee',
      ml: 360,
      kcal: 131,
      sugar: 9,
      caffeine: 90,
    },
    {
      title: '아이스 카푸치노',
      src: 'https://coffeebay.com/upload/menu/file_20200715141150.png',
      desc: '풍부하고 쫄깃한 우유 거품과 에스프레소가 조화로운 커피 음료',
      category: 'coffee',
      ml: 360,
      kcal: 89,
      sugar: 6,
      caffeine: 90,
    },
    {
      title: '아이스 바닐라 라떼',
      src: 'https://coffeebay.com/upload/menu/file_20200715134731.png',
      desc: '달콤한 바닐라 향과 풍부한 풍미를 지닌 에스프레소가 조화를 이루는 커피 음료',
      category: 'coffee',
      ml: 360,
      kcal: 179,
      sugar: 20,
      caffeine: 90,
    },
    {
      title: '아이스 헤이즐넛 라떼',
      src: 'https://coffeebay.com/upload/menu/file_20200715141714.png',
      desc: '고소하고 달콤한 헤이즐넛 향과 에스프레소가 조화를 이루는 커피 음료',
      category: 'coffee',
      ml: 360,
      kcal: 171,
      sugar: 23,
      caffeine: 80,
    },
    {
      title: '아이스 카라멜 마끼아또',
      src: 'https://coffeebay.com/upload/menu/file_20200715140905.png',
      desc: '진한 카라멜의 달콤함과 쫄깃하고 부드러운 우유 거품, 진한 에스프레소가 조화로운 커피 음료',
      category: 'coffee',
      ml: 360,
      kcal: 250,
      sugar: 36,
      caffeine: 90,
    },
    {
      title: '아이스 카페모카',
      src: 'https://coffeebay.com/upload/menu/file_20210120110302.png',
      desc: '달콤한 초콜릿, 깊은 맛의 에스프레소를 더해 휘핑크림으로 마무리한 커피 음료',
      category: 'coffee',
      ml: 360,
      kcal: 326,
      sugar: 36,
      caffeine: 90,
    },
    {
      title: '브라운슈가 버블 라떼',
      src: 'https://coffeebay.com/upload/menu/file_20200715135322.png',
      desc: '커피베이 에스프레소에 흑당을 더해, 더욱 깊어진 풍미를 즐길 수 있는 음료',
      category: 'coffee',
      ml: 550,
      kcal: 488,
      sugar: 60,
      caffeine: 180,
    },
    {
      title: '애플망고 선셋 티 에이드',
      src: 'https://coffeebay.com/upload/menu/file_20210325134625.png',
      desc: '애플망고에 향긋한 후르츠티를 더한 에이드',
      category: 'tea',
      ml: 550,
      kcal: 169,
      sugar: 25,
      caffeine: 0,
    },  
    {
      title: '크림 소다 펄 에이드',
      src: 'https://coffeebay.com/upload/menu/file_20200827174728.png',
      desc: '누구나 아는 ‘그 맛’을 트랜디한 크림폼으로 재해석한 버블 에이드',
      category: 'tea',
      ml: 550,
      kcal: 416,
      sugar: 47,
      caffeine: 0,
    },
    {
      title: '애플망고 스파클링 에이드',
      src: 'https://coffeebay.com/upload/menu/file_20210325135019.png',
      desc: '애플망고를 듬뿍! 상큼한 스파클링 에이드',
      category: 'tea',
      ml: 550,
      kcal: 169,
      sugar: 25,
      caffeine: 0,
    },
    {
      title: '리얼 수박 주스',
      src: 'https://coffeebay.com/upload/menu/file_20210603110245.png',
      desc: '시원 달콤! 빨갛게 잘 익은 수박 맛 그대로!',
      category: 'tea',
      ml: 550,
      kcal: 131,
      sugar: 19,
      caffeine: 0,
    },
    {
      title: '청포도 펄 에이드',
      src: 'https://coffeebay.com/upload/menu/file_20210603110141.png',
      desc: '상큼한 청포도에 탱글탱글 펄을 더한 스파클링 에이드',
      category: 'tea',
      ml: 550,
      kcal: 190,
      sugar: 33,
      caffeine: 0,
    },
    {
      title: '달고나 크런치 프라노베',
      src: 'https://coffeebay.com/upload/menu/file_20200713144026.png',
      desc: '부드러운 달고나 쉐이크에 바삭한 크런치와 쫄깃한 펄로 씹는 재미를 더한 음료',
      category: 'smoothie',
      ml: 550,
      kcal: 434,
      sugar: 56,
      caffeine: 0,
    },
    {
      title: '쿠키앤크림 프라노베',
      src: 'https://coffeebay.com/upload/menu/file_20200908180646.png',
      desc: '쿠키와 바닐라를 블랜딩하여 부드럽고 달콤하게 즐기는 아이스 블렌디드 음료',
      category: 'smoothie',
      ml: 360,
      kcal: 295,
      sugar: 45,
      caffeine: 0,
    },
    {
      title: '자바칩 프라노베',
      src: 'https://coffeebay.com/upload/menu/file_20210518134303.png',
      desc: '진하고 달콤한 자바칩을 그대로 느낄 수 있는 아이스 블렌디드 음료',
      category: 'smoothie',
      ml: 360,
      kcal: 414,
      sugar: 40,
      caffeine: 0,
    },
    {
      title: '카라멜 프라노베',
      src: 'https://coffeebay.com/upload/menu/file_20200715140933.png',
      desc: '진한 에스프레소와 풍부한 카라멜 맛을 느낄 수 있는 아이스 블렌디드 음료',
      category: 'smoothie',
      ml: 360,
      kcal: 369,
      sugar: 45,
      caffeine: 0,
    },


  ]

//로고
// 'https://t1.daumcdn.net/cfile/tistory/9989D4425B1E3C9501'
//배너
// 'https://coffeebay.com/upload/file_20210608125447.jpg'
//원두설명
// 커피베이는 5가지 아라비카 원두를 최적의 배합 비율로 블랜딩하여 가장 맛있는 커피 맛을 구현하였습니다 또한 신선한 원두만을 사용하기 때문에 그 향과 맛을 그대로 살릴 수 있는 태우지 않는 미디엄 로스팅 방식을 고수합니다.
//원두이미지
// 'https://coffeebay.com/extension/front/images/img_coffeebay_story02.png'