export const dalcomData = [
    {
      title: '드래곤후르츠 자몽에이드',
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/app_thumb_earlysummer_Dragon-3dhjcm2d3qd5ylmwpqcave.jpg',
      desc: '이국적인 느낌을 선사해주는 용과와 상큼달콤한 자몽의 과즙을 가득 담은 에이드',
      category: 'tea', 
      ml: 470,
      kcal: 115,
      sugar: 21,
      caffeine: 0,
    },
    {
      title: '패션후르츠 레몬에이드',
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/app_thumb_earlysummer_Passion-3dhjcvhm7ocae8malp7h8q.jpg',
      desc: '새콤하고 톡톡 터지는 패션후르츠에 푸른빛을 더해, 휴양지 해변을 연상시키는 에이드',
      category: 'tea',
      ml: 470,
      kcal: 141,
      sugar: 34,
      caffeine: 0,
    },
    {
      title: '얼그레이 크림라떼',
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/app_thumb_tavalon_creamlatte-3dhjdo4y2dv81at2f7cz62.jpg',
      desc: '타바론 얼그레이 크림이 풍성하게 얹어져 향긋하고 부드럽게 즐길 수 있는 에스프레소 TEA 라떼',
      category: 'coffee',
      ml: 355,
      kcal: 275,
      sugar: 23,
      caffeine: 52,
    },
    {
      title: '라임바질 티에이드',
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/app_thumb_tavalon_limebasil-1-3dhjdu62gfg9fmmwws8g7e.jpg',
      desc: 'TAVALON 캐모마일 TEA와 프레쉬한 생라임과 바질을 더해 청량감과 신선함을 느낄 수 있는 음료',
      category: 'tea',
      ml: 470,
      kcal: 115,
      sugar: 50,
      caffeine: 0,
    },
    {
      title: '자몽 얼그레이 아이스티',
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/app_thumb_grapefruit_tea_ice-3dhjp2drfo51voxj0hztai.jpg',
      desc: '달콤쌉싸름한 자몽과 얼그레이의 조합으로 깔끔한 음료와 생자몽 과육이 씹혀 상큼하게 마시는 음료',
      category: 'tea',
      ml: 470,
      kcal: 104,
      sugar: 36,
      caffeine: 0,
    },
    {
      title: '데일리 클린주스 레몬밀싹',
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/app_thumb_ls-3dhkdej8xut4pyuntu5yiy.png',
      desc: '과일과 채소를 콜드프레스 방식으로 가공한 100% 착츱 해독 쥬스',
      category: 'tea',
      ml: 355,
      kcal: 213,
      sugar: 22,
      caffeine: 0,
    },
    {
      title: '에스프레소', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/hot0004-3dhl9p1i4u7d6swngcofey.jpg',
      desc: '과일의 달콤함과 산미가 중후한 바디감. 원두 선택이 가능(Mild , Rich , Deep)',
      category: 'coffee',
      ml: 60,
      kcal: 6,
      sugar: 0,
      caffeine: 90,
    },
    {
      title: '에스프레소 마끼아또', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/Espresso-Macchiato-3dhl5sfujfrncin3g0sphm.jpg',
      desc: '바디감이 중후하고 여운이 오래 남는 에스프레소 K3를 부드러운 거품과 함께 마시는 음료',
      category: 'coffee',
      ml: 70,
      kcal: 12,
      sugar: 2,
      caffeine: 90,
    },
    {
      title: '아메리카노', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/20200319172126_app_thumb_c_americano-3dhl8aj3v7xnzau6m4cu8a.png',
      desc: '1. 밀크 초콜릿의 부드러운 바디감, 건과일의 은은한 산미가 어우러진 아메리카노 2. 다크 초콜릿의 묵직함과 고사한 견과류의 풍미가 어우러진 아메리카노',
      category: 'coffee',
      ml: 355,
      kcal: 6,
      sugar: 0,
      caffeine: 184,
    },
    {
      title: '카페라떼', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/20200319172249_app_thumb_c_cafelatte-3dhl9wtyaz91ht6pc252x6.png',
      desc: '풍부한 에스프레소와 우유 거품이 일품인 카페라떼',
      category: 'coffee',
      ml: 355,
      kcal: 153,
      sugar: 13,
      caffeine: 184,
    },
    {
      title: '바닐라 라떼', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/20200319172911_app_thumb_c_vanilla-3dhl9eql4uhxatp5vbint6.png',
      desc: '바닐라향이 어우러진 달콤한 커피',
      category: 'coffee',
      ml: 355,
      kcal: 265,
      sugar: 20,
      caffeine: 90,
    },                
    {
      title: '카푸치노', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/2014/06/20200319172514_app_thumb_c_cappuccino.png',
      desc: '부드러운 우유거품이 가득한 풍미로운 카푸치노',
      category: 'coffee',
      ml: 355,
      kcal: 141,
      sugar: 12,
      caffeine: 90,
    },   
    {
      title: '모카 라떼', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/20200319173058_app_thumb_c_mocalatte-3dhl66igs7gqly8ql1i58q.png',
      desc: '진한 초코의 향과 맛이 어우러진 달콤한 커피',
      category: 'coffee',
      ml: 355,
      kcal: 283,
      sugar: 37,
      caffeine: 90,
    },  
    {
      title: '카라멜 마끼아또', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/Caramel-Macchiato-3dhl5m15mil1m1kmsud9my.png',
      desc: '진한 에스프레소와 부드러운 우유, 그리고 달콤한 캐러멜향이 어우러진 달콤한 커피',
      category: 'coffee',
      ml: 355,
      kcal: 289,
      sugar: 23,
      caffeine: 90,
    },  
    {
      title: '나나', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/detail_nana-3dhktyd35ac3c0gsbkv956.jpg',
      desc: '달콤한 바나나우유 얼음과 딸기의 조화가 어우러져  딸기 과육이 씹히는 맛이 재미있는 스페셜 음료',
      category: 'smoothie',
      ml: 355,
      kcal: 420,
      sugar: 55,
      caffeine: 0,
    },
    {
      title: '바나', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/detail_bana-3dhku8afmefyvufnr0h1xm.jpg',
      desc: '달콤한 바나나 우유얼음에 치즈가 토핑되어 더욱 부드럽고 달콤한 맛의 바나나 스페셜 음료',
      category: 'smoothie',
      ml: 355,
      kcal: 430,
      sugar: 52,
      caffeine: 0,
    },
    {
      title: '망고큐브', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/Mango-Cube-3dhkwvemlvxiokhmbrfeve.jpg',
      desc: '비타민 A가 풍부한 망고를 갈아 꿀과 함께 우유에 섞어 마시는 부드러운 망고 스무디',
      category: 'smoothie',
      ml: 355,
      kcal: 247,
      sugar: 27,
      caffeine: 0,
    },
    {
      title: '베리큐브', 
      src: 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/Strawberry-Cube-3dhkzchp7bu12ypqexiaru.jpg',
      desc: '비타민 C가 풍부한 딸기를 갈아 꿀과 함께 우유에 섞어 마시는 부드러운 딸기 라떼',
      category: 'smoothie',
      ml: 355,
      kcal: 239,
      sugar: 23,
      caffeine: 0,
    },          
]

// 브랜드 로고
// 'https://image.dalkomm.com/data/KOMM/uploads/renew/2020/03/2020_달콤_투명로고-1.png'
// 원두 설명
// 최고 품질로 선별된 최상급의 아라비카종을 사용하여 부드러운 맛과 향의 밸런스를 최적화시킨 프리미엄 블렌딩을 추구하며 명품 머신 라 심발리를 통해 추출되는 달.콤의 에스프레소는 커피를 처음 접하는 고객부터 커피 애호가 모두 만족할 수 있는 맛과 향을 자랑합니다.

// 배너
// 'https://image.dalkomm.com/data/KOMM/uploads/renew/bfi_thumb/2021_05_pc_earlysummer_main-3de2shwrj4q64bbsuo5csq.jpg'
// 원두 이미지
// 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXoYER66O3-VreNA12d9MibdnoD7y8auL_6w&usqp=CAU'